const RSVP_ENDPOINT='https://script.google.com/macros/s/AKfycbxfCDRtruPz5o5D3pEmB1iZjya_Cv7_kFIj5oywHEG2gYJmjkKwXCI-0B8d3rpMXoC0/exec';
const target=new Date("2026-08-29T20:00:00+03:00").getTime();
function tick(){let x=Math.max(0,target-Date.now()),d=Math.floor(x/86400000);x%=86400000;let h=Math.floor(x/3600000);
x%=3600000;let m=Math.floor(x/60000);x%=60000;let s=Math.floor(x/1000);days.textContent=String(d).padStart(2,"0");hours.textContent=String(h).padStart(2,"0");minutes.textContent=String(m).padStart(2,"0");seconds.textContent=String(s).padStart(2,"0")}tick();setInterval(tick,1000);
document.getElementById("rsvpForm").addEventListener("submit",async e=>{e.preventDefault();
let btn=document.getElementById("submitBtn"),msg=document.getElementById("msg"),data=new URLSearchParams();
data.set("name",document.getElementById("guestName").value.trim());
data.set("attendance",document.getElementById("attendance").value);
data.set("timestamp",new Date().toLocaleString("ro-RO"));
btn.disabled=true;btn.textContent="SE TRIMITE...";
try{await fetch(RSVP_ENDPOINT,{method:"POST",mode:"no-cors",headers:{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},body:data.toString()});
msg.textContent="Multumesc! Confirmarea ta a fost inregistrata. ðŸ¥‚";
e.target.reset()}catch(err){msg.textContent="A aparut o problema. Verifica publicarea Google Apps Script si incearca din nou."}finally{btn.disabled=false;btn.textContent="CONFIRMÄ‚ PREZENÈšA"}});
